services:
  - type: web
    name: ai-order-agent
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python main.py
