services:
  - type: web
    name: ai-order-agent
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
